# MARK: Provision EC2 Instance
- name: Stage 1 - Provision production EC2 instance
  hosts: localhost
  gather_facts: false
  vars:
    region: "us-east-1"
    image_id: "ami-0866a3c8686eaeeba"
    instance_type: "t2.small"
    security_group: "devops-assignmentg-2-prod-sg"
    key_name: "devops-assignment-2-prod-key"
    instance_name: "DevOpsAssignment2_Prod"

  tasks:
    # MARK: EC2 Key Pair
    - name: Delete EC2 Key if it exists
      ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
        state: absent

    - name: Create EC2 SSH key
      ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
      register: ec2_key

    - name: Save EC2 SSH key to file
      copy:
        content: "{{ ec2_key.key.private_key }}"
        dest: "{{ key_name }}.pem"
        mode: 0600


    # MARK: EC2 Instance
    - name: Launch T2 small instance on EC2
      ec2_instance:
        name: "{{ instance_name }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ security_group }}"
        image_id: "{{ image_id }}"
        region: "{{ region }}"
        state: started
        wait: yes
      register: ec2_result



    - name: Add new instance to host group via its public IP address
      add_host:
        hostname: "{{ ec2_result.instances[0].public_ip_address }}"
        groupname: ec2_prod
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ ec2_result.instances[0].public_ip_address }}"
        port: 22
        delay: 20
        timeout: 320
        state: started

# MARK: Install Docker
- name: Stage 2 - Install Docker on the Production EC2 Instance
  hosts: ec2_prod
  vars:
    ansible_ssh_private_key_file: devops-assignment-2-prod-key.pem
    remote_ec2_user: ubuntu
  remote_user: "{{ remote_ec2_user }}"
  become: true
  become_method: sudo

  tasks:
    - name: Add the Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt packages and install docker-ce
      apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: "{{ remote_ec2_user }}"
        groups: docker
        append: yes